// =================================================================
// AI MIDI Composer — gRPC contract (v1)
// Plugin <-> AI Composition Engine (ACE)
// =================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: aimidi/v1/aimidi.proto

package aimidiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Energy_Level int32

const (
	Energy_UNSPECIFIED Energy_Level = 0
	Energy_LOW         Energy_Level = 1
	Energy_MID         Energy_Level = 2
	Energy_HIGH        Energy_Level = 3
)

// Enum value maps for Energy_Level.
var (
	Energy_Level_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOW",
		2: "MID",
		3: "HIGH",
	}
	Energy_Level_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LOW":         1,
		"MID":         2,
		"HIGH":        3,
	}
)

func (x Energy_Level) Enum() *Energy_Level {
	p := new(Energy_Level)
	*p = x
	return p
}

func (x Energy_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Energy_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_aimidi_v1_aimidi_proto_enumTypes[0].Descriptor()
}

func (Energy_Level) Type() protoreflect.EnumType {
	return &file_aimidi_v1_aimidi_proto_enumTypes[0]
}

func (x Energy_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Energy_Level.Descriptor instead.
func (Energy_Level) EnumDescriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{1, 0}
}

// -----------------------------------------------------------------
// Music Blueprint (consumed by Music Theory Engine via ace-internal)
// -----------------------------------------------------------------
type MusicBlueprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int64                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`                     // reproducibility
	RootKey       string                 `protobuf:"bytes,2,opt,name=root_key,json=rootKey,proto3" json:"root_key,omitempty"` // "C", "C#", "Db", ...
	Scale         string                 `protobuf:"bytes,3,opt,name=scale,proto3" json:"scale,omitempty"`                    // "major", "minor", "dorian", ...
	Bpm           int32                  `protobuf:"varint,4,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Ppq           int32                  `protobuf:"varint,5,opt,name=ppq,proto3" json:"ppq,omitempty"` // 480 default
	Genres        []string               `protobuf:"bytes,6,rep,name=genres,proto3" json:"genres,omitempty"`
	Energy        *Energy                `protobuf:"bytes,7,opt,name=energy,proto3" json:"energy,omitempty"`
	Timeline      *Timeline              `protobuf:"bytes,8,opt,name=timeline,proto3" json:"timeline,omitempty"`
	Instruments   []*Instrument          `protobuf:"bytes,9,rep,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicBlueprint) Reset() {
	*x = MusicBlueprint{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicBlueprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicBlueprint) ProtoMessage() {}

func (x *MusicBlueprint) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicBlueprint.ProtoReflect.Descriptor instead.
func (*MusicBlueprint) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{0}
}

func (x *MusicBlueprint) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *MusicBlueprint) GetRootKey() string {
	if x != nil {
		return x.RootKey
	}
	return ""
}

func (x *MusicBlueprint) GetScale() string {
	if x != nil {
		return x.Scale
	}
	return ""
}

func (x *MusicBlueprint) GetBpm() int32 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *MusicBlueprint) GetPpq() int32 {
	if x != nil {
		return x.Ppq
	}
	return 0
}

func (x *MusicBlueprint) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MusicBlueprint) GetEnergy() *Energy {
	if x != nil {
		return x.Energy
	}
	return nil
}

func (x *MusicBlueprint) GetTimeline() *Timeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *MusicBlueprint) GetInstruments() []*Instrument {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type Energy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         Energy_Level           `protobuf:"varint,1,opt,name=level,proto3,enum=aimidi.v1.Energy_Level" json:"level,omitempty"`
	Density       float32                `protobuf:"fixed32,2,opt,name=density,proto3" json:"density,omitempty"`       // 0..1
	Complexity    float32                `protobuf:"fixed32,3,opt,name=complexity,proto3" json:"complexity,omitempty"` // 0..1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Energy) Reset() {
	*x = Energy{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Energy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Energy) ProtoMessage() {}

func (x *Energy) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Energy.ProtoReflect.Descriptor instead.
func (*Energy) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{1}
}

func (x *Energy) GetLevel() Energy_Level {
	if x != nil {
		return x.Level
	}
	return Energy_UNSPECIFIED
}

func (x *Energy) GetDensity() float32 {
	if x != nil {
		return x.Density
	}
	return 0
}

func (x *Energy) GetComplexity() float32 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

type Mood struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`           // ex.: "melancholic"
	Valence       float32                `protobuf:"fixed32,2,opt,name=valence,proto3" json:"valence,omitempty"`     // 0..1
	Arousal       float32                `protobuf:"fixed32,3,opt,name=arousal,proto3" json:"arousal,omitempty"`     // 0..1
	Dominance     float32                `protobuf:"fixed32,4,opt,name=dominance,proto3" json:"dominance,omitempty"` // 0..1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mood) Reset() {
	*x = Mood{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mood) ProtoMessage() {}

func (x *Mood) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mood.ProtoReflect.Descriptor instead.
func (*Mood) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{2}
}

func (x *Mood) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Mood) GetValence() float32 {
	if x != nil {
		return x.Valence
	}
	return 0
}

func (x *Mood) GetArousal() float32 {
	if x != nil {
		return x.Arousal
	}
	return 0
}

func (x *Mood) GetDominance() float32 {
	if x != nil {
		return x.Dominance
	}
	return 0
}

type Timeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeline) Reset() {
	*x = Timeline{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeline) ProtoMessage() {}

func (x *Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeline.ProtoReflect.Descriptor instead.
func (*Timeline) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{3}
}

func (x *Timeline) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "intro", "verse", "chorus", ...
	StartBar      int32                  `protobuf:"varint,2,opt,name=start_bar,json=startBar,proto3" json:"start_bar,omitempty"`
	Bars          int32                  `protobuf:"varint,3,opt,name=bars,proto3" json:"bars,omitempty"`
	Energy        *Energy                `protobuf:"bytes,4,opt,name=energy,proto3" json:"energy,omitempty"`
	Instruments   []*InstrumentRole      `protobuf:"bytes,5,rep,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{4}
}

func (x *Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Section) GetStartBar() int32 {
	if x != nil {
		return x.StartBar
	}
	return 0
}

func (x *Section) GetBars() int32 {
	if x != nil {
		return x.Bars
	}
	return 0
}

func (x *Section) GetEnergy() *Energy {
	if x != nil {
		return x.Energy
	}
	return nil
}

func (x *Section) GetInstruments() []*InstrumentRole {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type Instrument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`        // "lead"|"comping"|"rhythm"|"bass"|"drum"|"pad"
	Channel       uint32                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"` // 0..15
	Program       uint32                 `protobuf:"varint,4,opt,name=program,proto3" json:"program,omitempty"` // GM program
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instrument) Reset() {
	*x = Instrument{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument) ProtoMessage() {}

func (x *Instrument) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument.ProtoReflect.Descriptor instead.
func (*Instrument) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{5}
}

func (x *Instrument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instrument) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Instrument) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Instrument) GetProgram() uint32 {
	if x != nil {
		return x.Program
	}
	return 0
}

type InstrumentRole struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstrumentName string                 `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "lead"|"comping"|...
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstrumentRole) Reset() {
	*x = InstrumentRole{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentRole) ProtoMessage() {}

func (x *InstrumentRole) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentRole.ProtoReflect.Descriptor instead.
func (*InstrumentRole) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{6}
}

func (x *InstrumentRole) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

func (x *InstrumentRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// -----------------------------------------------------------------
// Workflows
// -----------------------------------------------------------------
type NewCompositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int64                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"` // user natural language
	StyleHint     string                 `protobuf:"bytes,3,opt,name=style_hint,json=styleHint,proto3" json:"style_hint,omitempty"`
	TargetSeconds int32                  `protobuf:"varint,4,opt,name=target_seconds,json=targetSeconds,proto3" json:"target_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewCompositionRequest) Reset() {
	*x = NewCompositionRequest{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewCompositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCompositionRequest) ProtoMessage() {}

func (x *NewCompositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCompositionRequest.ProtoReflect.Descriptor instead.
func (*NewCompositionRequest) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{7}
}

func (x *NewCompositionRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *NewCompositionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *NewCompositionRequest) GetStyleHint() string {
	if x != nil {
		return x.StyleHint
	}
	return ""
}

func (x *NewCompositionRequest) GetTargetSeconds() int32 {
	if x != nil {
		return x.TargetSeconds
	}
	return 0
}

type ContinueCompositionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Seed            int64                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	SharedContextId string                 `protobuf:"bytes,2,opt,name=shared_context_id,json=sharedContextId,proto3" json:"shared_context_id,omitempty"`
	FromBar         int32                  `protobuf:"varint,3,opt,name=from_bar,json=fromBar,proto3" json:"from_bar,omitempty"`
	BarsToAppend    int32                  `protobuf:"varint,4,opt,name=bars_to_append,json=barsToAppend,proto3" json:"bars_to_append,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContinueCompositionRequest) Reset() {
	*x = ContinueCompositionRequest{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueCompositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueCompositionRequest) ProtoMessage() {}

func (x *ContinueCompositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueCompositionRequest.ProtoReflect.Descriptor instead.
func (*ContinueCompositionRequest) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{8}
}

func (x *ContinueCompositionRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ContinueCompositionRequest) GetSharedContextId() string {
	if x != nil {
		return x.SharedContextId
	}
	return ""
}

func (x *ContinueCompositionRequest) GetFromBar() int32 {
	if x != nil {
		return x.FromBar
	}
	return 0
}

func (x *ContinueCompositionRequest) GetBarsToAppend() int32 {
	if x != nil {
		return x.BarsToAppend
	}
	return 0
}

type GenerateVariationsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseSeed        int64                  `protobuf:"varint,1,opt,name=base_seed,json=baseSeed,proto3" json:"base_seed,omitempty"`
	SharedContextId string                 `protobuf:"bytes,2,opt,name=shared_context_id,json=sharedContextId,proto3" json:"shared_context_id,omitempty"`
	VariationCount  int32                  `protobuf:"varint,3,opt,name=variation_count,json=variationCount,proto3" json:"variation_count,omitempty"`
	SeedSeedDelta   int64                  `protobuf:"varint,4,opt,name=seed_seed_delta,json=seedSeedDelta,proto3" json:"seed_seed_delta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateVariationsRequest) Reset() {
	*x = GenerateVariationsRequest{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVariationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVariationsRequest) ProtoMessage() {}

func (x *GenerateVariationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVariationsRequest.ProtoReflect.Descriptor instead.
func (*GenerateVariationsRequest) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateVariationsRequest) GetBaseSeed() int64 {
	if x != nil {
		return x.BaseSeed
	}
	return 0
}

func (x *GenerateVariationsRequest) GetSharedContextId() string {
	if x != nil {
		return x.SharedContextId
	}
	return ""
}

func (x *GenerateVariationsRequest) GetVariationCount() int32 {
	if x != nil {
		return x.VariationCount
	}
	return 0
}

func (x *GenerateVariationsRequest) GetSeedSeedDelta() int64 {
	if x != nil {
		return x.SeedSeedDelta
	}
	return 0
}

// -----------------------------------------------------------------
// Response
// -----------------------------------------------------------------
type CompositionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // empty on success
	SmfMidi         []byte                 `protobuf:"bytes,3,opt,name=smf_midi,json=smfMidi,proto3" json:"smf_midi,omitempty"`          // SMF1 Standard MIDI File (one trk/instr)
	LiveEvents      []*MicroEvent          `protobuf:"bytes,4,rep,name=live_events,json=liveEvents,proto3" json:"live_events,omitempty"` // buffer to push to Plugin
	SharedContextId string                 `protobuf:"bytes,5,opt,name=shared_context_id,json=sharedContextId,proto3" json:"shared_context_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompositionResponse) Reset() {
	*x = CompositionResponse{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositionResponse) ProtoMessage() {}

func (x *CompositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositionResponse.ProtoReflect.Descriptor instead.
func (*CompositionResponse) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{10}
}

func (x *CompositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompositionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompositionResponse) GetSmfMidi() []byte {
	if x != nil {
		return x.SmfMidi
	}
	return nil
}

func (x *CompositionResponse) GetLiveEvents() []*MicroEvent {
	if x != nil {
		return x.LiveEvents
	}
	return nil
}

func (x *CompositionResponse) GetSharedContextId() string {
	if x != nil {
		return x.SharedContextId
	}
	return ""
}

type MicroEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickOn        uint32                 `protobuf:"varint,1,opt,name=tick_on,json=tickOn,proto3" json:"tick_on,omitempty"`
	TickOff       uint32                 `protobuf:"varint,2,opt,name=tick_off,json=tickOff,proto3" json:"tick_off,omitempty"`
	Channel       uint32                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Note          uint32                 `protobuf:"varint,4,opt,name=note,proto3" json:"note,omitempty"`
	Velocity      uint32                 `protobuf:"varint,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Articulation  uint32                 `protobuf:"varint,6,opt,name=articulation,proto3" json:"articulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroEvent) Reset() {
	*x = MicroEvent{}
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroEvent) ProtoMessage() {}

func (x *MicroEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aimidi_v1_aimidi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroEvent.ProtoReflect.Descriptor instead.
func (*MicroEvent) Descriptor() ([]byte, []int) {
	return file_aimidi_v1_aimidi_proto_rawDescGZIP(), []int{11}
}

func (x *MicroEvent) GetTickOn() uint32 {
	if x != nil {
		return x.TickOn
	}
	return 0
}

func (x *MicroEvent) GetTickOff() uint32 {
	if x != nil {
		return x.TickOff
	}
	return 0
}

func (x *MicroEvent) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *MicroEvent) GetNote() uint32 {
	if x != nil {
		return x.Note
	}
	return 0
}

func (x *MicroEvent) GetVelocity() uint32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *MicroEvent) GetArticulation() uint32 {
	if x != nil {
		return x.Articulation
	}
	return 0
}

var File_aimidi_v1_aimidi_proto protoreflect.FileDescriptor

const file_aimidi_v1_aimidi_proto_rawDesc = "" +
	"\n" +
	"\x16aimidi/v1/aimidi.proto\x12\taimidi.v1\"\xa6\x02\n" +
	"\x0eMusicBlueprint\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x03R\x04seed\x12\x19\n" +
	"\broot_key\x18\x02 \x01(\tR\arootKey\x12\x14\n" +
	"\x05scale\x18\x03 \x01(\tR\x05scale\x12\x10\n" +
	"\x03bpm\x18\x04 \x01(\x05R\x03bpm\x12\x10\n" +
	"\x03ppq\x18\x05 \x01(\x05R\x03ppq\x12\x16\n" +
	"\x06genres\x18\x06 \x03(\tR\x06genres\x12)\n" +
	"\x06energy\x18\a \x01(\v2\x11.aimidi.v1.EnergyR\x06energy\x12/\n" +
	"\btimeline\x18\b \x01(\v2\x13.aimidi.v1.TimelineR\btimeline\x127\n" +
	"\vinstruments\x18\t \x03(\v2\x15.aimidi.v1.InstrumentR\vinstruments\"\xa7\x01\n" +
	"\x06Energy\x12-\n" +
	"\x05level\x18\x01 \x01(\x0e2\x17.aimidi.v1.Energy.LevelR\x05level\x12\x18\n" +
	"\adensity\x18\x02 \x01(\x02R\adensity\x12\x1e\n" +
	"\n" +
	"complexity\x18\x03 \x01(\x02R\n" +
	"complexity\"4\n" +
	"\x05Level\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\a\n" +
	"\x03MID\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\"n\n" +
	"\x04Mood\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x18\n" +
	"\avalence\x18\x02 \x01(\x02R\avalence\x12\x18\n" +
	"\aarousal\x18\x03 \x01(\x02R\aarousal\x12\x1c\n" +
	"\tdominance\x18\x04 \x01(\x02R\tdominance\":\n" +
	"\bTimeline\x12.\n" +
	"\bsections\x18\x01 \x03(\v2\x12.aimidi.v1.SectionR\bsections\"\xb6\x01\n" +
	"\aSection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tstart_bar\x18\x02 \x01(\x05R\bstartBar\x12\x12\n" +
	"\x04bars\x18\x03 \x01(\x05R\x04bars\x12)\n" +
	"\x06energy\x18\x04 \x01(\v2\x11.aimidi.v1.EnergyR\x06energy\x12;\n" +
	"\vinstruments\x18\x05 \x03(\v2\x19.aimidi.v1.InstrumentRoleR\vinstruments\"h\n" +
	"\n" +
	"Instrument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x18\n" +
	"\aprogram\x18\x04 \x01(\rR\aprogram\"M\n" +
	"\x0eInstrumentRole\x12'\n" +
	"\x0finstrument_name\x18\x01 \x01(\tR\x0einstrumentName\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x89\x01\n" +
	"\x15NewCompositionRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x03R\x04seed\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"style_hint\x18\x03 \x01(\tR\tstyleHint\x12%\n" +
	"\x0etarget_seconds\x18\x04 \x01(\x05R\rtargetSeconds\"\x9d\x01\n" +
	"\x1aContinueCompositionRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x03R\x04seed\x12*\n" +
	"\x11shared_context_id\x18\x02 \x01(\tR\x0fsharedContextId\x12\x19\n" +
	"\bfrom_bar\x18\x03 \x01(\x05R\afromBar\x12$\n" +
	"\x0ebars_to_append\x18\x04 \x01(\x05R\fbarsToAppend\"\xb5\x01\n" +
	"\x19GenerateVariationsRequest\x12\x1b\n" +
	"\tbase_seed\x18\x01 \x01(\x03R\bbaseSeed\x12*\n" +
	"\x11shared_context_id\x18\x02 \x01(\tR\x0fsharedContextId\x12'\n" +
	"\x0fvariation_count\x18\x03 \x01(\x05R\x0evariationCount\x12&\n" +
	"\x0fseed_seed_delta\x18\x04 \x01(\x03R\rseedSeedDelta\"\xc4\x01\n" +
	"\x13CompositionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bsmf_midi\x18\x03 \x01(\fR\asmfMidi\x126\n" +
	"\vlive_events\x18\x04 \x03(\v2\x15.aimidi.v1.MicroEventR\n" +
	"liveEvents\x12*\n" +
	"\x11shared_context_id\x18\x05 \x01(\tR\x0fsharedContextId\"\xae\x01\n" +
	"\n" +
	"MicroEvent\x12\x17\n" +
	"\atick_on\x18\x01 \x01(\rR\x06tickOn\x12\x19\n" +
	"\btick_off\x18\x02 \x01(\rR\atickOff\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x12\n" +
	"\x04note\x18\x04 \x01(\rR\x04note\x12\x1a\n" +
	"\bvelocity\x18\x05 \x01(\rR\bvelocity\x12\"\n" +
	"\farticulation\x18\x06 \x01(\rR\farticulation2\xa2\x02\n" +
	"\x12CompositionService\x12R\n" +
	"\x0eNewComposition\x12 .aimidi.v1.NewCompositionRequest\x1a\x1e.aimidi.v1.CompositionResponse\x12\\\n" +
	"\x13ContinueComposition\x12%.aimidi.v1.ContinueCompositionRequest\x1a\x1e.aimidi.v1.CompositionResponse\x12Z\n" +
	"\x12GenerateVariations\x12$.aimidi.v1.GenerateVariationsRequest\x1a\x1e.aimidi.v1.CompositionResponseB7Z5aimidi.composer/ace/internal/proto/aimidi/v1;aimidiv1b\x06proto3"

var (
	file_aimidi_v1_aimidi_proto_rawDescOnce sync.Once
	file_aimidi_v1_aimidi_proto_rawDescData []byte
)

func file_aimidi_v1_aimidi_proto_rawDescGZIP() []byte {
	file_aimidi_v1_aimidi_proto_rawDescOnce.Do(func() {
		file_aimidi_v1_aimidi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aimidi_v1_aimidi_proto_rawDesc), len(file_aimidi_v1_aimidi_proto_rawDesc)))
	})
	return file_aimidi_v1_aimidi_proto_rawDescData
}

var file_aimidi_v1_aimidi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aimidi_v1_aimidi_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_aimidi_v1_aimidi_proto_goTypes = []any{
	(Energy_Level)(0),                  // 0: aimidi.v1.Energy.Level
	(*MusicBlueprint)(nil),             // 1: aimidi.v1.MusicBlueprint
	(*Energy)(nil),                     // 2: aimidi.v1.Energy
	(*Mood)(nil),                       // 3: aimidi.v1.Mood
	(*Timeline)(nil),                   // 4: aimidi.v1.Timeline
	(*Section)(nil),                    // 5: aimidi.v1.Section
	(*Instrument)(nil),                 // 6: aimidi.v1.Instrument
	(*InstrumentRole)(nil),             // 7: aimidi.v1.InstrumentRole
	(*NewCompositionRequest)(nil),      // 8: aimidi.v1.NewCompositionRequest
	(*ContinueCompositionRequest)(nil), // 9: aimidi.v1.ContinueCompositionRequest
	(*GenerateVariationsRequest)(nil),  // 10: aimidi.v1.GenerateVariationsRequest
	(*CompositionResponse)(nil),        // 11: aimidi.v1.CompositionResponse
	(*MicroEvent)(nil),                 // 12: aimidi.v1.MicroEvent
}
var file_aimidi_v1_aimidi_proto_depIdxs = []int32{
	2,  // 0: aimidi.v1.MusicBlueprint.energy:type_name -> aimidi.v1.Energy
	4,  // 1: aimidi.v1.MusicBlueprint.timeline:type_name -> aimidi.v1.Timeline
	6,  // 2: aimidi.v1.MusicBlueprint.instruments:type_name -> aimidi.v1.Instrument
	0,  // 3: aimidi.v1.Energy.level:type_name -> aimidi.v1.Energy.Level
	5,  // 4: aimidi.v1.Timeline.sections:type_name -> aimidi.v1.Section
	2,  // 5: aimidi.v1.Section.energy:type_name -> aimidi.v1.Energy
	7,  // 6: aimidi.v1.Section.instruments:type_name -> aimidi.v1.InstrumentRole
	12, // 7: aimidi.v1.CompositionResponse.live_events:type_name -> aimidi.v1.MicroEvent
	8,  // 8: aimidi.v1.CompositionService.NewComposition:input_type -> aimidi.v1.NewCompositionRequest
	9,  // 9: aimidi.v1.CompositionService.ContinueComposition:input_type -> aimidi.v1.ContinueCompositionRequest
	10, // 10: aimidi.v1.CompositionService.GenerateVariations:input_type -> aimidi.v1.GenerateVariationsRequest
	11, // 11: aimidi.v1.CompositionService.NewComposition:output_type -> aimidi.v1.CompositionResponse
	11, // 12: aimidi.v1.CompositionService.ContinueComposition:output_type -> aimidi.v1.CompositionResponse
	11, // 13: aimidi.v1.CompositionService.GenerateVariations:output_type -> aimidi.v1.CompositionResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_aimidi_v1_aimidi_proto_init() }
func file_aimidi_v1_aimidi_proto_init() {
	if File_aimidi_v1_aimidi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aimidi_v1_aimidi_proto_rawDesc), len(file_aimidi_v1_aimidi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aimidi_v1_aimidi_proto_goTypes,
		DependencyIndexes: file_aimidi_v1_aimidi_proto_depIdxs,
		EnumInfos:         file_aimidi_v1_aimidi_proto_enumTypes,
		MessageInfos:      file_aimidi_v1_aimidi_proto_msgTypes,
	}.Build()
	File_aimidi_v1_aimidi_proto = out.File
	file_aimidi_v1_aimidi_proto_goTypes = nil
	file_aimidi_v1_aimidi_proto_depIdxs = nil
}
