// =================================================================
// AI MIDI Composer — gRPC contract (v1)
// Plugin <-> AI Composition Engine (ACE)
// =================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: aimidi/v1/aimidi.proto

package aimidiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompositionService_NewComposition_FullMethodName      = "/aimidi.v1.CompositionService/NewComposition"
	CompositionService_ContinueComposition_FullMethodName = "/aimidi.v1.CompositionService/ContinueComposition"
	CompositionService_GenerateVariations_FullMethodName  = "/aimidi.v1.CompositionService/GenerateVariations"
)

// CompositionServiceClient is the client API for CompositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -----------------------------------------------------------------
// Workflow Request / Response envelopes
// -----------------------------------------------------------------
type CompositionServiceClient interface {
	// Workflow 1: New Composition from prompt
	NewComposition(ctx context.Context, in *NewCompositionRequest, opts ...grpc.CallOption) (*CompositionResponse, error)
	// Workflow 4: Continue Composition
	ContinueComposition(ctx context.Context, in *ContinueCompositionRequest, opts ...grpc.CallOption) (*CompositionResponse, error)
	// Workflow 6: Generate Variations
	GenerateVariations(ctx context.Context, in *GenerateVariationsRequest, opts ...grpc.CallOption) (*CompositionResponse, error)
}

type compositionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompositionServiceClient(cc grpc.ClientConnInterface) CompositionServiceClient {
	return &compositionServiceClient{cc}
}

func (c *compositionServiceClient) NewComposition(ctx context.Context, in *NewCompositionRequest, opts ...grpc.CallOption) (*CompositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompositionResponse)
	err := c.cc.Invoke(ctx, CompositionService_NewComposition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compositionServiceClient) ContinueComposition(ctx context.Context, in *ContinueCompositionRequest, opts ...grpc.CallOption) (*CompositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompositionResponse)
	err := c.cc.Invoke(ctx, CompositionService_ContinueComposition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compositionServiceClient) GenerateVariations(ctx context.Context, in *GenerateVariationsRequest, opts ...grpc.CallOption) (*CompositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompositionResponse)
	err := c.cc.Invoke(ctx, CompositionService_GenerateVariations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompositionServiceServer is the server API for CompositionService service.
// All implementations must embed UnimplementedCompositionServiceServer
// for forward compatibility.
//
// -----------------------------------------------------------------
// Workflow Request / Response envelopes
// -----------------------------------------------------------------
type CompositionServiceServer interface {
	// Workflow 1: New Composition from prompt
	NewComposition(context.Context, *NewCompositionRequest) (*CompositionResponse, error)
	// Workflow 4: Continue Composition
	ContinueComposition(context.Context, *ContinueCompositionRequest) (*CompositionResponse, error)
	// Workflow 6: Generate Variations
	GenerateVariations(context.Context, *GenerateVariationsRequest) (*CompositionResponse, error)
	mustEmbedUnimplementedCompositionServiceServer()
}

// UnimplementedCompositionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompositionServiceServer struct{}

func (UnimplementedCompositionServiceServer) NewComposition(context.Context, *NewCompositionRequest) (*CompositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewComposition not implemented")
}
func (UnimplementedCompositionServiceServer) ContinueComposition(context.Context, *ContinueCompositionRequest) (*CompositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinueComposition not implemented")
}
func (UnimplementedCompositionServiceServer) GenerateVariations(context.Context, *GenerateVariationsRequest) (*CompositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateVariations not implemented")
}
func (UnimplementedCompositionServiceServer) mustEmbedUnimplementedCompositionServiceServer() {}
func (UnimplementedCompositionServiceServer) testEmbeddedByValue()                            {}

// UnsafeCompositionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompositionServiceServer will
// result in compilation errors.
type UnsafeCompositionServiceServer interface {
	mustEmbedUnimplementedCompositionServiceServer()
}

func RegisterCompositionServiceServer(s grpc.ServiceRegistrar, srv CompositionServiceServer) {
	// If the following call panics, it indicates UnimplementedCompositionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompositionService_ServiceDesc, srv)
}

func _CompositionService_NewComposition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCompositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompositionServiceServer).NewComposition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompositionService_NewComposition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompositionServiceServer).NewComposition(ctx, req.(*NewCompositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompositionService_ContinueComposition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueCompositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompositionServiceServer).ContinueComposition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompositionService_ContinueComposition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompositionServiceServer).ContinueComposition(ctx, req.(*ContinueCompositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompositionService_GenerateVariations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVariationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompositionServiceServer).GenerateVariations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompositionService_GenerateVariations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompositionServiceServer).GenerateVariations(ctx, req.(*GenerateVariationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompositionService_ServiceDesc is the grpc.ServiceDesc for CompositionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompositionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aimidi.v1.CompositionService",
	HandlerType: (*CompositionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewComposition",
			Handler:    _CompositionService_NewComposition_Handler,
		},
		{
			MethodName: "ContinueComposition",
			Handler:    _CompositionService_ContinueComposition_Handler,
		},
		{
			MethodName: "GenerateVariations",
			Handler:    _CompositionService_GenerateVariations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aimidi/v1/aimidi.proto",
}
